# ruff: noqa: UP042
"""Enterprise Open AML Adapter Pydantic v2 Schemas (Phase 110).

Drop-in API compatibility schemas implementing standard European / International
AML OpenAPI specifications for:
- Person / Legal Entity ingestion and UBO corporate hierarchy
- Real-time online transaction monitoring checks and offline scenario runs
- High-throughput fuzzy Sanctions & PEP screening searches
- Webhook dispatch envelopes and verification payloads
"""

from __future__ import annotations

import secrets
import uuid
from datetime import UTC, datetime
from decimal import Decimal
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

# ── Enumerations ─────────────────────────────────────────────────────────────

class PersonType(str, Enum):
    """Subject legal classification."""
    INDIVIDUAL = "INDIVIDUAL"
    LEGAL_ENTITY = "LEGAL_ENTITY"


class PersonStatus(str, Enum):
    """Subject compliance lifecycle status."""
    ACTIVE = "ACTIVE"
    BLOCKED = "BLOCKED"
    UNDER_REVIEW = "UNDER_REVIEW"
    INACTIVE = "INACTIVE"


class DocumentType(str, Enum):
    """Identity or corporate registration document type."""
    PASSPORT = "PASSPORT"
    NATIONAL_ID = "NATIONAL_ID"
    DRIVING_LICENSE = "DRIVING_LICENSE"
    RESIDENCE_PERMIT = "RESIDENCE_PERMIT"
    CERTIFICATE_OF_INCORPORATION = "CERTIFICATE_OF_INCORPORATION"
    ARTICLES_OF_ASSOCIATION = "ARTICLES_OF_ASSOCIATION"
    TAX_IDENTIFIER = "TAX_IDENTIFIER"
    OTHER = "OTHER"


class MonitoringMode(str, Enum):
    """Execution mode for AML transaction monitoring."""
    ONLINE = "ONLINE"    # Synchronous blocking/allowing real-time evaluation (<50ms)
    OFFLINE = "OFFLINE"  # Asynchronous background batch/scenario audit


class MonitoringAction(str, Enum):
    """Actionable compliance decision resulting from transaction monitoring."""
    ALLOW = "ALLOW"
    REVIEW = "REVIEW"
    BLOCK = "BLOCK"


class OpenAMLScreeningDisposition(str, Enum):
    """Decision category for screening searches."""
    CLEAR = "CLEAR"
    POTENTIAL_MATCH = "POTENTIAL_MATCH"
    MATCH = "MATCH"


class OpenAMLWebhookEventType(str, Enum):
    """Event types generated by the Open AML adapter pipeline."""
    ALERT_CREATED = "ALERT_CREATED"
    ALERT_STATUS_UPDATED = "ALERT_STATUS_UPDATED"
    SCREENING_ALERT_CREATED = "SCREENING_ALERT_CREATED"
    FINAL_RISK_UPDATED = "FINAL_RISK_UPDATED"


# ── Reusable Component Models ────────────────────────────────────────────────

class Address(BaseModel):
    """Standardized physical address model."""
    model_config = ConfigDict(extra="ignore")

    street: str | None = None
    building_number: str | None = None
    postal_code: str | None = None
    city: str | None = None
    state: str | None = None
    country: str = Field(..., min_length=2, max_length=2, description="ISO 3166-1 alpha-2 country code")

    @field_validator("country")
    @classmethod
    def normalize_country(cls, v: str) -> str:
        return v.strip().upper()


class Document(BaseModel):
    """Identification or verification document model."""
    model_config = ConfigDict(extra="ignore")

    document_type: DocumentType = DocumentType.PASSPORT
    document_number: str = Field(..., min_length=1, max_length=64)
    issuing_country: str = Field("DE", min_length=2, max_length=2)
    issue_date: str | None = None
    expiry_date: str | None = None

    @field_validator("issuing_country")
    @classmethod
    def normalize_country(cls, v: str) -> str:
        return v.strip().upper()


class UBORecord(BaseModel):
    """Ultimate Beneficial Owner or key corporate principal relation."""
    model_config = ConfigDict(extra="ignore")

    ubo_person_id: str = Field(default_factory=lambda: f"UBO-{uuid.uuid4().hex[:8].upper()}", description="Unique person_id of the beneficial owner")
    ubo_name: str = Field(default="", description="Full legal name of the natural person UBO")
    ownership_percentage: float = Field(..., ge=0.0, le=100.0, description="Direct or indirect equity/voting percentage")
    relationship_type: str = Field("BENEFICIAL_OWNER", description="SHAREHOLDER, DIRECTOR, BENEFICIAL_OWNER, TRUSTEE")
    is_pep: bool = Field(default=False, description="Politically Exposed Person flag")
    country_of_residence: str | None = Field(default=None, max_length=2)

    @model_validator(mode="before")
    @classmethod
    def _coerce_ubo_fields(cls, data: Any) -> Any:
        if isinstance(data, dict):
            if "full_name" in data and not data.get("ubo_name"):
                data["ubo_name"] = data["full_name"]
            if "name" in data and not data.get("ubo_name"):
                data["ubo_name"] = data["name"]
        return data


# ── Person Ingestion Models ──────────────────────────────────────────────────

class PersonCreateRequest(BaseModel):
    """Drop-in request to register an individual customer or legal entity."""
    model_config = ConfigDict(extra="ignore")

    person_id: str = Field(default_factory=lambda: f"PER-{uuid.uuid4().hex[:12].upper()}", max_length=128, description="Institution-unique customer identifier")
    person_type: PersonType = Field(default=PersonType.INDIVIDUAL)
    first_name: str | None = None
    last_name: str | None = None
    legal_name: str | None = None
    registration_number: str | None = None
    date_of_birth: str | None = None
    nationality: str | None = Field(default=None, max_length=2)
    country_of_residence: str | None = Field(default=None, max_length=2)
    addresses: list[Address] = Field(default_factory=list)
    documents: list[Document] = Field(default_factory=list)
    ubo_records: list[UBORecord] = Field(default_factory=list)
    email: str | None = None
    phone: str | None = None
    client_status: PersonStatus = Field(default=PersonStatus.ACTIVE)
    metadata: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def _coerce_person_fields(cls, data: Any) -> Any:
        if isinstance(data, dict):
            if "company_name" in data and not data.get("legal_name"):
                data["legal_name"] = data["company_name"]
            if "ubos" in data and not data.get("ubo_records"):
                data["ubo_records"] = data["ubos"]
            if "status" in data and not data.get("client_status"):
                data["client_status"] = data["status"]
        return data

    @field_validator("nationality", "country_of_residence")
    @classmethod
    def normalize_country_opt(cls, v: str | None) -> str | None:
        if v:
            return v.strip().upper()
        return v

    def resolved_display_name(self) -> str:
        """Derive authoritative display name across Individual and Legal Entity schemas."""
        if self.person_type == PersonType.LEGAL_ENTITY and self.legal_name:
            return self.legal_name.strip()
        parts = [p for p in (self.first_name, self.last_name) if p and p.strip()]
        if parts:
            return " ".join(parts).strip()
        return self.legal_name or self.person_id


class PersonResponse(BaseModel):
    """Standardized representation of registered person or corporate entity."""
    model_config = ConfigDict(extra="ignore")

    person_id: str
    person_type: PersonType
    display_name: str
    first_name: str | None = None
    last_name: str | None = None
    legal_name: str | None = None
    company_name: str | None = None
    registration_number: str | None = None
    date_of_birth: str | None = None
    nationality: str | None = None
    country_of_residence: str | None = None
    addresses_count: int
    documents_count: int
    ubo_count: int
    client_status: PersonStatus
    risk_tier: str = "STANDARD"
    created_at: str
    updated_at: str
    metadata: dict[str, Any] = Field(default_factory=dict)


# ── Transaction & Monitoring Check Models ────────────────────────────────────

class PersonTransactionCreateRequest(BaseModel):
    """Standardized transaction ingestion associated with a registered person."""
    model_config = ConfigDict(extra="ignore")

    transaction_id: str = Field(default_factory=lambda: f"TX-{uuid.uuid4().hex[:12].upper()}", max_length=128)
    amount: Decimal = Field(..., gt=Decimal("0.0"), description="Transaction value in specified currency")
    currency: str = Field(default="EUR", min_length=3, max_length=3)
    direction: str = Field(default="OUTBOUND", description="INBOUND or OUTBOUND")
    counterparty_name: str = Field(default="UNKNOWN_COUNTERPARTY", max_length=256)
    counterparty_account: str = Field(default="UNKNOWN_ACCOUNT", max_length=128)
    counterparty_bank_bic: str | None = None
    counterparty_country: str | None = Field(default=None, max_length=2)
    payment_method: str = Field(default="SEPA_INSTANT", description="SEPA_INSTANT, WIRE, CARD, ACH, CRYPTO")
    reference: str | None = None
    merchant_category: str | None = None
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))

    @model_validator(mode="before")
    @classmethod
    def _coerce_txn_fields(cls, data: Any) -> Any:
        if isinstance(data, dict):
            if "external_transaction_id" in data and not data.get("transaction_id"):
                data["transaction_id"] = data["external_transaction_id"]
            if "counterparty_iban" in data and not data.get("counterparty_account"):
                data["counterparty_account"] = data["counterparty_iban"]
            if "beneficiary_country" in data and not data.get("counterparty_country"):
                data["counterparty_country"] = data["beneficiary_country"]
        return data

    @field_validator("currency", "counterparty_country")
    @classmethod
    def normalize_upper(cls, v: str | None) -> str | None:
        if v:
            return v.strip().upper()
        return v


class PersonTransactionResponse(BaseModel):
    """Response returned upon ingesting a transaction."""
    model_config = ConfigDict(extra="ignore")

    transaction_id: str
    person_id: str
    amount: float
    currency: str
    direction: str
    counterparty_name: str
    counterparty_account: str
    payment_method: str
    timestamp: str
    recorded_at: str


class MonitoringCheckRequest(BaseModel):
    """Request to evaluate a financial transaction against real-time AML engines."""
    model_config = ConfigDict(extra="ignore")

    transaction_id: str = Field(default="", max_length=128)
    mode: MonitoringMode = Field(default=MonitoringMode.ONLINE)
    evaluate_scenarios: list[str] = Field(default_factory=list)
    client_metadata: dict[str, Any] = Field(default_factory=dict)


class MonitoringCheckResponse(BaseModel):
    """Actionable monitoring decision with explainability breakdown."""
    model_config = ConfigDict(extra="ignore")

    check_id: str
    transaction_id: str
    person_id: str
    mode: MonitoringMode
    action: MonitoringAction
    composite_risk_score: int = Field(..., ge=0, le=1000)
    triggered_rules: list[str] = Field(default_factory=list)
    triggered_scenarios: list[str] = Field(default_factory=list)
    signals_summary: dict[str, float] = Field(default_factory=dict)
    rule_explanations: list[str] = Field(default_factory=list)
    decision_timestamp: str
    latency_ms: float


# ── Sanctions & PEP Screening Compatibility Models ───────────────────────────

class OpenAMLScreeningCheckRequest(BaseModel):
    """Screening search payload targeting a registered person or ad-hoc subject."""
    model_config = ConfigDict(extra="ignore")

    person_id: str | None = None
    target_name: str | None = None
    date_of_birth: str | None = None
    nationality: str | None = None
    threshold: float = Field(default=0.75, ge=0.50, le=1.00)
    lists_to_check: list[str] = Field(
        default_factory=lambda: ["UN", "EU_CFSP", "OFAC_SDN", "PEP"],
        description="Filter specific lists (UN, EU_CFSP, OFAC_SDN, PEP, GOODLIST)",
    )

    @model_validator(mode="before")
    @classmethod
    def _coerce_screening_fields(cls, data: Any) -> Any:
        if isinstance(data, dict):
            if "query_name" in data and not data.get("target_name"):
                data["target_name"] = data["query_name"]
            if "match_threshold" in data:
                mt = float(data["match_threshold"])
                if mt > 1.0:
                    data["threshold"] = min(1.0, max(0.50, mt / 100.0))
                else:
                    data["threshold"] = min(1.0, max(0.50, mt))
        return data


class ScreeningHit(BaseModel):
    """Individual matched watchlist entity."""
    model_config = ConfigDict(extra="ignore")

    watchlist_source: str
    matched_name: str
    composite_score: float
    algorithm: str
    entity_type: str
    date_of_birth_matched: bool
    nationality_matched: bool
    sanctions_program: str | None = None


class OpenAMLScreeningCheckResponse(BaseModel):
    """Results of sanctions and PEP watchlist evaluation."""
    model_config = ConfigDict(extra="ignore")

    search_id: str
    person_id: str | None = None
    searched_name: str
    decision: OpenAMLScreeningDisposition
    highest_score: float
    hit_count: int
    matches: list[ScreeningHit] = Field(default_factory=list)
    whitelist_bypassed: bool = False
    timestamp: str
    latency_ms: float


# ── Webhook Models ───────────────────────────────────────────────────────────

class OpenAMLWebhookSubscriptionRequest(BaseModel):
    """Payload to register an external webhook listener for AML events."""
    model_config = ConfigDict(extra="ignore")

    target_url: str = Field(default="", max_length=512)
    secret_key: str = Field(default_factory=lambda: secrets.token_hex(24), min_length=16, max_length=128)
    events: list[OpenAMLWebhookEventType] = Field(
        default_factory=lambda: [
            OpenAMLWebhookEventType.ALERT_CREATED,
            OpenAMLWebhookEventType.SCREENING_ALERT_CREATED,
            OpenAMLWebhookEventType.FINAL_RISK_UPDATED,
        ]
    )

    @model_validator(mode="before")
    @classmethod
    def _coerce_webhook_fields(cls, data: Any) -> Any:
        if isinstance(data, dict) and "callback_url" in data and not data.get("target_url"):
            data["target_url"] = data["callback_url"]
        return data


class OpenAMLWebhookSubscriptionResponse(BaseModel):
    """Confirmation of webhook subscription."""
    model_config = ConfigDict(extra="ignore")

    subscription_id: str
    target_url: str
    signing_secret: str | None = None
    subscribed_events: list[OpenAMLWebhookEventType]
    created_at: str
    status: str = "ACTIVE"


class OpenAMLWebhookEvent(BaseModel):
    """Outbound webhook envelope dispatched to core banking systems."""
    model_config = ConfigDict(extra="ignore")

    event_id: str
    event_type: OpenAMLWebhookEventType
    timestamp: str
    tenant_id: str
    payload: dict[str, Any]
    signature_sha256: str


# ── Telemetry & Metrics Models ───────────────────────────────────────────────

class OpenAMLAdapterMetricsResponse(BaseModel):
    """Operational telemetry for the drop-in AML adapter."""
    model_config = ConfigDict(extra="ignore")

    total_persons_registered: int
    total_transactions_ingested: int
    total_monitoring_checks: int
    total_screening_checks: int
    total_webhooks_dispatched: int
    active_subscriptions_count: int
    p95_online_check_latency_ms: float
    status: str = "HEALTHY"
    adapter_version: str = "2.0.0"

