"""Phase 2 domain entities.

Core business objects for the AML intelligence platform.
These extend the Phase 1 entities with alert management, case
investigations, entity resolution, and shared intelligence concepts.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any

from app.domain.enums import (
    AlertSeverity,
    AlertStatus,
    CasePriority,
    CaseStatus,
    EntityType,
    IntelligenceType,
    RelationshipType,
    RiskLevel,
    ScenarioType,
    TriageAction,
    TriagePriority,
)


@dataclass
class Alert:
    """A fraud alert generated by a bank's detection pipeline.

    Alerts are the primary output of the risk engine. They never contain
    raw transaction data — only risk scores, reason codes, and
    privacy-preserving entity identifiers.
    """

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    bank_id: str = ""
    transaction_id: str = ""
    risk_score: float = 0.0
    severity: AlertSeverity = AlertSeverity.MEDIUM
    status: AlertStatus = AlertStatus.NEW
    reason_codes: list[str] = field(default_factory=list)
    confidence: float = 0.0
    involved_entity_ids: list[str] = field(default_factory=list)
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime | None = None

    # Explainability
    top_features: list[dict[str, float | str]] = field(default_factory=list)
    risk_factors: list[str] = field(default_factory=list)
    model_confidence: float = 0.0
    historical_evidence: list[str] = field(default_factory=list)

    # Triage & Deduplication
    triage_priority: TriagePriority = TriagePriority.P3_MEDIUM
    triage_action: TriageAction = TriageAction.QUEUE_STANDARD
    sla_minutes: int = 1440
    triage_reasons: list[str] = field(default_factory=list)
    dedup_key: str | None = None
    dedup_count: int = 1
    is_duplicate: bool = False
    first_seen_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    last_duplicate_at: datetime | None = None

    @property
    def is_actionable(self) -> bool:
        """Whether this alert requires investigation."""
        return self.severity in (AlertSeverity.CRITICAL, AlertSeverity.HIGH) or self.triage_priority in (
            TriagePriority.P1_CRITICAL,
            TriagePriority.P2_HIGH,
        )


@dataclass
class Case:
    """An investigation case linking multiple alerts.

    Cases track the investigation lifecycle from initial detection
    through resolution. They aggregate evidence from multiple alerts
    and support collaborative investigation workflows.
    """

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    title: str = ""
    status: CaseStatus = CaseStatus.OPEN
    priority: CasePriority = CasePriority.P3_MEDIUM
    assigned_to: str | None = None
    alert_ids: list[str] = field(default_factory=list)
    notes: list[CaseNote] = field(default_factory=list)
    timeline: list[CaseEvent] = field(default_factory=list)
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime | None = None
    closed_at: datetime | None = None
    total_risk_score: float = 0.0
    evidence_ids: list[str] = field(default_factory=list)
    supervisor_signatures: list[str] = field(default_factory=list)

    @property
    def supervisor_signature(self) -> str | None:
        """Legacy accessor returning primary supervisor signature if present."""
        return self.supervisor_signatures[0] if self.supervisor_signatures else None

    @supervisor_signature.setter
    def supervisor_signature(self, value: str | None) -> None:
        """Legacy setter appending a signature if not already present."""
        if value and value not in self.supervisor_signatures:
            self.supervisor_signatures.append(value)

    @property
    def is_open(self) -> bool:
        return self.status not in (
            CaseStatus.CLOSED_CONFIRMED,
            CaseStatus.CLOSED_FALSE_POSITIVE,
        )

    @property
    def duration_hours(self) -> float | None:
        end = self.closed_at or datetime.now(UTC)
        return (end - self.created_at).total_seconds() / 3600



@dataclass
class CaseNote:
    """An investigation note attached to a case."""

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    case_id: str = ""
    author: str = "analyst"
    content: str = ""
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))


@dataclass
class CaseEvent:
    """A timestamped event in a case's investigation timeline."""

    event_type: str = ""  # "created", "status_changed", "note_added", "alert_linked"
    description: str = ""
    actor: str = "system"
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))
    metadata: dict = field(default_factory=dict)


@dataclass
class Entity:
    """A privacy-preserving entity in the financial crime graph.

    Entities represent real-world objects (customers, merchants, devices, etc.)
    identified by deterministic hashes rather than raw PII. This enables
    cross-institution entity matching without exposing private information.
    """

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    entity_type: EntityType = EntityType.CUSTOMER
    privacy_id: str = ""  # HMAC-SHA256 hash of the raw identifier
    bank_id: str = ""
    display_label: str = ""  # e.g. "CUST-a3f2", "MERCH-8b1c" (non-PII)
    attributes: dict = field(default_factory=dict)  # Non-sensitive metadata
    risk_level: RiskLevel = RiskLevel.MINIMAL
    alert_count: int = 0
    first_seen: datetime = field(default_factory=lambda: datetime.now(UTC))
    last_seen: datetime = field(default_factory=lambda: datetime.now(UTC))


@dataclass
class Relationship:
    """An edge in the entity relationship graph.

    Represents a known connection between two entities with a confidence
    score and supporting evidence.
    """

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    source_entity_id: str = ""
    target_entity_id: str = ""
    relationship_type: RelationshipType = RelationshipType.OWNS
    confidence: float = 1.0
    evidence: list[str] | dict[str, Any] = field(default_factory=list)  # Alert IDs, transaction hashes, or metadata dict
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))


@dataclass
class SharedIntelligence:
    """Cross-institution intelligence published to the shared layer.

    This is what banks share with each other — never raw transactions.
    It contains only hashed identifiers, risk indicators, and pattern
    descriptions that other institutions can correlate against their
    own data.
    """

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    source_bank_id: str = ""
    intelligence_type: IntelligenceType = IntelligenceType.FRAUD_ALERT
    privacy_hash: str = ""  # Hashed entity identifier
    risk_indicator: float = 0.0
    description: str = ""
    entity_type: EntityType | None = None
    related_alert_count: int = 0
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    expires_at: datetime | None = None


@dataclass
class StreamingEvent:
    """A real-time event for WebSocket streaming.

    Used during scenario replay to simulate live transaction monitoring.
    """

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    event_type: str = ""  # "transaction", "alert", "intelligence", "entity_resolved"
    bank_id: str = ""
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))
    payload: dict = field(default_factory=dict)
    delay_ms: int = 0  # Delay before this event fires (for scenario pacing)


@dataclass
class Scenario:
    """A pre-built fraud scenario for simulation.

    Scenarios generate a scripted sequence of events that demonstrate
    how collaborative intelligence improves detection. Each scenario
    involves multiple banks observing fragments of the same fraud.
    """

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    scenario_type: ScenarioType = ScenarioType.FRAUD_RING
    name: str = ""
    description: str = ""
    banks_involved: list[str] = field(default_factory=list)
    events: list[StreamingEvent] = field(default_factory=list)
    duration_seconds: float = 0.0
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))


@dataclass
class Evidence:
    """An evidence registry entry linked to a case."""

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    case_id: str = ""
    evidence_type: str = ""  # "document", "kyc_profile", "ledger_proof"
    title: str = ""
    file_path: str = ""
    content_hash: str = ""  # SHA-256 hash of the evidence details/content
    uploaded_by: str = ""
    uploaded_at: datetime = field(default_factory=lambda: datetime.now(UTC))



@dataclass
class InvestigatorAuditLog:
    """An audit log entry for investigator query operations."""

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    investigator: str = ""
    action: str = ""  # "access_case", "query_entity", "cross_bank_resolve", etc.
    target_id: str = ""
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))
    session_duration_sec: float | None = None
    metadata: dict = field(default_factory=dict)


# ── Phase 106: Inter-Bank Encrypted FININT Bridge Ticket ──────────────────────


@dataclass
class FinintTicketAuditEntry:
    """Immutable audit trail entry for a FININT bridge ticket lifecycle event.

    Each entry is hash-chained to its predecessor using SHA-256 to ensure
    tamper-evident chronological ordering of all compliance officer actions.
    """

    seq: int = 0
    actor: str = ""  # anonymised officer identifier (HMAC-SHA256 of staff ID)
    action: str = ""  # state transition or evidence action
    previous_status: str = ""
    new_status: str = ""
    event_hash: str = ""  # SHA-256(prev_hash || seq || actor || action || ts)
    previous_hash: str = ""
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class FinintBridgeTicket:
    """Encrypted inter-bank FININT case ticket for cross-institution intelligence exchange.

    Implements the European Collaborative FININT information-sharing protocol:
    - Payload is AES-GCM encrypted with an ephemeral key derived via Curve25519 ECDH.
    - Evidence attachments are verified by SHA-256 content hashes.
    - Lifecycle transitions are audit-logged with SHA-256 hash-chaining.
    - Zero raw PII is transmitted; all entity identifiers are HMAC-SHA256 hashes.
    """

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    ticket_type: str = ""  # FinintTicketType value
    status: str = "OPEN"  # FinintTicketStatus value
    originating_bank_id: str = ""  # HMAC-SHA256 identifier of requesting institution
    recipient_bank_id: str = ""  # HMAC-SHA256 identifier of receiving institution

    # Encrypted payload (AES-GCM / Curve25519)
    encrypted_payload: str = ""  # base64url-encoded ciphertext
    payload_nonce: str = ""  # base64url-encoded 96-bit GCM nonce
    ephemeral_public_key: str = ""  # base64url-encoded Curve25519 public key

    # Evidence attachments — never raw files, only hashes
    evidence_hashes: list[str] = field(default_factory=list)  # SHA-256 of each attachment

    # Lifecycle
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    closed_at: datetime | None = None
    sla_hours: int = 4  # Maximum response SLA for URGENT_FREEZE_REQUEST = 4h per EPC SEPA

    # Audit chain
    audit_trail: list[FinintTicketAuditEntry] = field(default_factory=list)
    head_hash: str = ""  # current tip of the hash chain

