import React from 'react';
import { describe, it, expect, beforeEach, vi } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import CaseDetailPage from '../CaseDetailPage';

import { apiClient } from '../../api/client';

const mockCase = {
  id: 'case_001',
  title: 'Suspected Cross-Border Smurfing Ring',
  status: 'investigating',
  priority: 'high',
  assigned_to: 'analyst_01',
  alert_ids: ['ALT_101', 'ALT_102'],
  evidence_ids: [],
  notes: [
    {
      id: 'note_1',
      case_id: 'case_001',
      author: 'supervisor_alice',
      content: 'High velocity observed across bank_alpha and bank_beta.',
      created_at: '2026-08-14T08:00:00Z',
    },
  ],
  timeline: [
    {
      id: 'evt_1',
      case_id: 'case_001',
      event_type: 'created',
      description: 'Case auto-generated by ML ensemble alert',
      created_by: 'system',
      created_at: '2026-08-14T07:30:00Z',
    },
  ],
  created_at: '2026-08-14T07:30:00Z',
  updated_at: '2026-08-14T08:00:00Z',
  closed_at: null,
  total_risk_score: 840,
  duration_hours: 4.5,
  is_open: true,
};

const createWrapper = (initialRoute = '/cases/case_001') => {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: { retry: false },
    },
  });
  return ({ children }: { children: React.ReactNode }) => (
    <QueryClientProvider client={queryClient}>
      <MemoryRouter initialEntries={[initialRoute]}>
        <Routes>
          <Route path="/cases/:caseId" element={children} />
        </Routes>
      </MemoryRouter>
    </QueryClientProvider>
  );
};

describe('CaseDetailPage', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
    sessionStorage.clear();
    vi.spyOn(apiClient, 'get').mockImplementation(async (url: string) => {
      if (url.includes('/evidence')) {
        return { data: [] };
      }
      return { data: mockCase };
    });
  });

  it('renders case detail layout, timeline, and evidence ledger sections', async () => {
    render(<CaseDetailPage />, { wrapper: createWrapper() });

    await waitFor(() => {
      expect(screen.getByText(/Suspected Cross-Border Smurfing Ring/i)).toBeInTheDocument();
    });
    expect(screen.getByText(/Autonomous Agentic AML Copilot & RAG Narrative/i)).toBeInTheDocument();
    expect(screen.getByText(/Supervisor Signature:/i)).toBeInTheDocument();
    expect(screen.getByText(/Case Evidence Registry/i)).toBeInTheDocument();
  });

  it('allows typing a note in the case notes input area', async () => {
    render(<CaseDetailPage />, { wrapper: createWrapper() });

    await waitFor(() => {
      expect(screen.getByPlaceholderText(/Add an investigation note/i)).toBeInTheDocument();
    });

    const textarea = screen.getByPlaceholderText(/Add an investigation note/i);
    fireEvent.change(textarea, { target: { value: 'Investigated IP cluster 192.168.1.1' } });
    expect(textarea).toHaveValue('Investigated IP cluster 192.168.1.1');
  });

  it('allows filling in evidence details (type, title, path)', async () => {
    render(<CaseDetailPage />, { wrapper: createWrapper() });

    await waitFor(() => {
      expect(screen.getByPlaceholderText(/e\.g\. Identity Proof/i)).toBeInTheDocument();
    });

    const titleInput = screen.getByPlaceholderText(/e\.g\. Identity Proof/i);
    fireEvent.change(titleInput, { target: { value: 'KYC Passport Verification' } });
    expect(titleInput).toHaveValue('KYC Passport Verification');
  });

  it('renders Suspect Entities & Graph Topology Hub with 2-Hop/3-Hop graph deep links for evidence and selected alert', async () => {
    const mockEvidenceItem = {
      id: 'evi_99',
      case_id: 'case_001',
      evidence_type: 'device_fingerprint',
      title: 'Mule Device IMEI Cluster',
      file_path: 'dev_fraud_442',
      content_hash: 'sha256_mock_hash_xyz',
      uploaded_by: 'investigator_bob',
      uploaded_at: '2026-08-14T09:00:00Z',
    };

    const mockAlertDetail = {
      id: 'ALT_101',
      bank_id: 'bank_alpha',
      account_id: 'ent_acc_smurf_9981',
      device_id: 'dev_fraud_442',
      involved_entity_ids: ['cust_linked_99', 'dev_pos_441'],
      risk_score: 910,
      severity: 'critical',
      status: 'new',
      created_at: '2026-08-14T07:15:00Z',
      reason_codes: ['HIGH-VELOCITY', 'STRUCTURING'],
      top_features: [{ feature: 'velocity_burst', contribution: 0.65 }],
      risk_factors: ['High burst rate'],
      model_confidence: 0.94,
    };

    vi.spyOn(apiClient, 'get').mockImplementation(async (url: string) => {
      if (url.includes('/evidence')) {
        return { data: [mockEvidenceItem] };
      }
      if (url.includes('/alerts/ALT_101')) {
        return { data: mockAlertDetail };
      }
      return { data: mockCase };
    });

    render(<CaseDetailPage />, { wrapper: createWrapper() });

    // Verify Suspect Entities & Graph Topology Hub appears with evidence entity
    await waitFor(() => {
      expect(screen.getByText(/Suspect Entities & Graph Topology Hub/i)).toBeInTheDocument();
    });
    expect(screen.getAllByText('dev_fraud_442').length).toBeGreaterThanOrEqual(1);

    // Verify 2-Hop and 3-Hop links for evidence entity
    const twoHopLinks = screen.getAllByRole('link', { name: /2-Hop/i });
    const hasEvidence2Hop = twoHopLinks.some(
      (link) => link.getAttribute('href') === '/graph?entity_id=dev_fraud_442&depth=2'
    );
    expect(hasEvidence2Hop).toBe(true);

    const threeHopLinks = screen.getAllByRole('link', { name: /3-Hop/i });
    const hasEvidence3Hop = threeHopLinks.some(
      (link) => link.getAttribute('href') === '/graph?entity_id=dev_fraud_442&depth=3'
    );
    expect(hasEvidence3Hop).toBe(true);

    // Verify Evidence table has 2-Hop Graph link
    const tableGraphLinks = screen.getAllByRole('link', { name: /2-Hop Graph/i });
    expect(tableGraphLinks[0]).toHaveAttribute('href', '/graph?entity_id=dev_fraud_442&depth=2');

    // Click on Alert ALT_101 to select alert and verify alert's involved entity ids join the hub
    const alertBtn = screen.getByRole('button', { name: /ALT_101/i });
    fireEvent.click(alertBtn);

    await waitFor(() => {
      expect(screen.getAllByText('cust_linked_99').length).toBeGreaterThanOrEqual(1);
    });
    expect(screen.getAllByText('dev_pos_441').length).toBeGreaterThanOrEqual(1);

    // Verify 2-Hop link exists for cust_linked_99
    const updatedTwoHopLinks = screen.getAllByRole('link', { name: /2-Hop/i });
    const hasAlertEntity2Hop = updatedTwoHopLinks.some(
      (link) => link.getAttribute('href') === '/graph?entity_id=cust_linked_99&depth=2'
    );
    expect(hasAlertEntity2Hop).toBe(true);
  });

  it('restores generated Copilot SAR narrative from sessionStorage (cfi_copilot_case_${caseId}) across component mounts', async () => {
    const mockCopilotResponse = {
      case_id: 'case_001',
      fincen_sar_narrative:
        'FinCEN SAR Narrative Part V: Suspect entity ent_acc_smurf_9981 engaged in rapid structuring across bank_alpha and bank_beta.',
      four_eyes_briefing:
        'Supervisor Briefing: Critical structuring pattern detected across 2 institutional nodes.',
      recommended_action: 'escalate_sar_filing',
      top_risk_drivers: [
        { feature: 'cross_bank_velocity_ratio', impact: 0.88, description: 'Rapid fund transfers exceeding 8x peer median' },
        { feature: 'device_fingerprint_mule_cluster', impact: 0.72, description: 'Shared IMEI across 3 non-resident accounts' },
      ],
      graph_topology_summary: { total_nodes: 12, total_edges: 28, cycle_detected: true },
      zero_pii_verified: true,
      generated_at: '2026-08-14T09:30:00Z',
      lineage_hash: 'sha256_mock_copilot_lineage_0123456789abcdef',
    };

    // Pre-populate sessionStorage with case-specific key
    sessionStorage.setItem('cfi_copilot_case_case_001', JSON.stringify(mockCopilotResponse));

    render(<CaseDetailPage />, { wrapper: createWrapper() });

    // Verify narrative is immediately restored from sessionStorage without calling generation API
    await waitFor(() => {
      expect(screen.getByText(/FinCEN SAR Narrative Part V/i)).toBeInTheDocument();
    });
    expect(screen.getByText(/Restored from Session Cache/i)).toBeInTheDocument();
    expect(screen.getByText(/Supervisor Briefing: Critical structuring pattern/i)).toBeInTheDocument();
    expect(screen.getByText('cross_bank_velocity_ratio')).toBeInTheDocument();
    expect(screen.getByText('+88.0%')).toBeInTheDocument();
    expect(screen.getByText(/Regenerate Narrative/i)).toBeInTheDocument();
    expect(screen.getByRole('button', { name: /Clear Cache/i })).toBeInTheDocument();
  });

  it('persists newly generated Copilot SAR narrative to sessionStorage (cfi_copilot_case_${caseId})', async () => {
    const mockCopilotResponse = {
      case_id: 'case_001',
      fincen_sar_narrative:
        'Newly generated FinCEN SAR Narrative: High risk structuring detected across consortium.',
      four_eyes_briefing:
        'Supervisor Briefing: High confidence ML anomaly.',
      recommended_action: 'escalate_sar_filing',
      top_risk_drivers: [
        { feature: 'high_velocity_anomaly', impact: 0.91 },
      ],
      graph_topology_summary: { total_nodes: 8, total_edges: 14 },
      zero_pii_verified: true,
      generated_at: '2026-08-14T10:00:00Z',
      lineage_hash: 'sha256_fresh_hash_9876543210',
    };

    vi.spyOn(apiClient, 'post').mockImplementation(async (url: string) => {
      if (url.includes('/copilot/narrative')) {
        return { data: mockCopilotResponse };
      }
      return { data: {} };
    });

    render(<CaseDetailPage />, { wrapper: createWrapper() });

    // Initially no narrative exists in sessionStorage
    expect(sessionStorage.getItem('cfi_copilot_case_case_001')).toBeNull();

    // Wait for case to load and click Generate AI SAR Narrative
    const generateBtn = await screen.findByRole('button', { name: /Generate AI SAR Narrative/i });
    fireEvent.click(generateBtn);

    // Verify narrative is rendered
    await waitFor(() => {
      expect(screen.getByText(/Newly generated FinCEN SAR Narrative/i)).toBeInTheDocument();
    });

    // Verify it is saved to sessionStorage under cfi_copilot_case_case_001
    const stored = sessionStorage.getItem('cfi_copilot_case_case_001');
    expect(stored).not.toBeNull();
    const parsed = JSON.parse(stored!);
    expect(parsed.fincen_sar_narrative).toBe(mockCopilotResponse.fincen_sar_narrative);
    expect(parsed.lineage_hash).toBe('sha256_fresh_hash_9876543210');
  });

  it('clears cached Copilot SAR narrative and resets session storage when Clear Cache is clicked', async () => {
    const mockCopilotResponse = {
      case_id: 'case_001',
      fincen_sar_narrative: 'Existing cached SAR narrative to be purged.',
      four_eyes_briefing: 'Supervisor briefing to be cleared.',
      recommended_action: 'review_pending',
      top_risk_drivers: [{ feature: 'amount_skew', impact: 0.65 }],
      graph_topology_summary: {},
      zero_pii_verified: true,
      generated_at: '2026-08-14T08:00:00Z',
      lineage_hash: 'sha256_purge_hash',
    };

    sessionStorage.setItem('cfi_copilot_case_case_001', JSON.stringify(mockCopilotResponse));

    render(<CaseDetailPage />, { wrapper: createWrapper() });

    await waitFor(() => {
      expect(screen.getByText(/Existing cached SAR narrative to be purged/i)).toBeInTheDocument();
    });

    // Click Clear Cache button
    const clearBtn = screen.getByRole('button', { name: /Clear Cache/i });
    fireEvent.click(clearBtn);

    // Verify narrative is removed from view and button reverts to initial state
    await waitFor(() => {
      expect(screen.queryByText(/Existing cached SAR narrative to be purged/i)).not.toBeInTheDocument();
    });
    expect(screen.getByRole('button', { name: /Generate AI SAR Narrative/i })).toBeInTheDocument();

    // Verify sessionStorage item is removed
    expect(sessionStorage.getItem('cfi_copilot_case_case_001')).toBeNull();
  });
});


