import React from 'react';
import { describe, it, expect, beforeEach, vi } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import CaseDetailPage from '../CaseDetailPage';

import { apiClient } from '../../api/client';

const mockCase = {
  id: 'case_001',
  title: 'Suspected Cross-Border Smurfing Ring',
  status: 'investigating',
  priority: 'high',
  assigned_to: 'analyst_01',
  alert_ids: ['ALT_101', 'ALT_102'],
  evidence_ids: [],
  notes: [
    {
      id: 'note_1',
      case_id: 'case_001',
      author: 'supervisor_alice',
      content: 'High velocity observed across bank_alpha and bank_beta.',
      created_at: '2026-08-14T08:00:00Z',
    },
  ],
  timeline: [
    {
      id: 'evt_1',
      case_id: 'case_001',
      event_type: 'created',
      description: 'Case auto-generated by ML ensemble alert',
      created_by: 'system',
      created_at: '2026-08-14T07:30:00Z',
    },
  ],
  created_at: '2026-08-14T07:30:00Z',
  updated_at: '2026-08-14T08:00:00Z',
  closed_at: null,
  total_risk_score: 840,
  duration_hours: 4.5,
  is_open: true,
};

const createWrapper = (initialRoute = '/cases/case_001') => {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: { retry: false },
    },
  });
  return ({ children }: { children: React.ReactNode }) => (
    <QueryClientProvider client={queryClient}>
      <MemoryRouter initialEntries={[initialRoute]}>
        <Routes>
          <Route path="/cases/:caseId" element={children} />
        </Routes>
      </MemoryRouter>
    </QueryClientProvider>
  );
};

describe('CaseDetailPage', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
    vi.spyOn(apiClient, 'get').mockImplementation(async (url: string) => {
      if (url.includes('/evidence')) {
        return { data: [] };
      }
      return { data: mockCase };
    });
  });

  it('renders case detail layout, timeline, and evidence ledger sections', async () => {
    render(<CaseDetailPage />, { wrapper: createWrapper() });

    await waitFor(() => {
      expect(screen.getByText(/Suspected Cross-Border Smurfing Ring/i)).toBeInTheDocument();
    });
    expect(screen.getByText(/Autonomous Agentic AML Copilot & RAG Narrative/i)).toBeInTheDocument();
    expect(screen.getByText(/Supervisor Signature:/i)).toBeInTheDocument();
    expect(screen.getByText(/Case Evidence Registry/i)).toBeInTheDocument();
  });

  it('allows typing a note in the case notes input area', async () => {
    render(<CaseDetailPage />, { wrapper: createWrapper() });

    await waitFor(() => {
      expect(screen.getByPlaceholderText(/Add an investigation note/i)).toBeInTheDocument();
    });

    const textarea = screen.getByPlaceholderText(/Add an investigation note/i);
    fireEvent.change(textarea, { target: { value: 'Investigated IP cluster 192.168.1.1' } });
    expect(textarea).toHaveValue('Investigated IP cluster 192.168.1.1');
  });

  it('allows filling in evidence details (type, title, path)', async () => {
    render(<CaseDetailPage />, { wrapper: createWrapper() });

    await waitFor(() => {
      expect(screen.getByPlaceholderText(/e\.g\. Identity Proof/i)).toBeInTheDocument();
    });

    const titleInput = screen.getByPlaceholderText(/e\.g\. Identity Proof/i);
    fireEvent.change(titleInput, { target: { value: 'KYC Passport Verification' } });
    expect(titleInput).toHaveValue('KYC Passport Verification');
  });
});
