apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "cfi-platform-hpa"
  labels:
    app.kubernetes.io/name: cfi-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "cfi-platform-deployment"
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}

