apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "cfi-platform-ingress"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/limit-rps: "500"
spec:
  ingressClassName: "nginx"
  tls:
    - secretName: cfi-tls-cert
      hosts:
        - cfi.bank-consortium.org
  rules:
    - host: "cfi.bank-consortium.org"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "cfi-platform-service"
                port:
                  number: 8000

