apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "cfi-platform-ingress"
  labels:
    app.kubernetes.io/name: cfi-platform
  annotations:
    cert-manager.io/cluster-issuer: {{ index .Values.ingress.annotations "cert-manager.io/cluster-issuer" | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ index .Values.ingress.annotations "nginx.ingress.kubernetes.io/proxy-body-size" | quote }}
    nginx.ingress.kubernetes.io/limit-rps: {{ index .Values.ingress.annotations "nginx.ingress.kubernetes.io/limit-rps" | quote }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  tls:
    - hosts:
        - {{ index (index .Values.ingress.tls 0).hosts 0 | quote }}
      secretName: {{ (index .Values.ingress.tls 0).secretName | quote }}
  rules:
    - host: {{ (index .Values.ingress.hosts 0).host | quote }}
      http:
        paths:
          - path: {{ (index (index .Values.ingress.hosts 0).paths 0).path | quote }}
            pathType: {{ (index (index .Values.ingress.hosts 0).paths 0).pathType | quote }}
            backend:
              service:
                name: "cfi-platform-service"
                port:
                  number: {{ .Values.service.port }}

