apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "{{ .Release.Name }}-coordinator-pdb"
  labels:
    app.kubernetes.io/name: cfi-coordinator
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: coordinator
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cfi-coordinator
      app.kubernetes.io/instance: "{{ .Release.Name }}"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "{{ .Release.Name }}-fraud-alert-pdb"
  labels:
    app.kubernetes.io/name: cfi-fraud-alert
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: fraud-alert
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cfi-fraud-alert
      app.kubernetes.io/instance: "{{ .Release.Name }}"
