import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MemoryRouter, Routes, Route } from 'react-router-dom';
import InvestigationDashboard from '../../pages/InvestigationDashboard';
import AlertsPage from '../../pages/AlertsPage';
import CasesPage from '../../pages/CasesPage';
import CaseDetailPage from '../../pages/CaseDetailPage';
import Layout from '../../components/layout/Layout';
import { apiClient } from '../../api/client';

describe('Integration: AML Investigation, Alerts & Cryptographic Case Ledger', () => {
  const createWrapper = (initialRoute = '/cases/case_909') => {
    const queryClient = new QueryClient({
      defaultOptions: { queries: { retry: false } },
    });

    return ({ children }: { children?: React.ReactNode }) => (
      <QueryClientProvider client={queryClient}>
        <MemoryRouter initialEntries={[initialRoute]}>
          <Routes>
            <Route element={<Layout />}>
              <Route path="/investigation" element={<InvestigationDashboard />} />
              <Route path="/alerts" element={<AlertsPage />} />
              <Route path="/cases" element={<CasesPage />} />
              <Route path="/cases/:caseId" element={<CaseDetailPage />} />
            </Route>
          </Routes>
          {children}
        </MemoryRouter>
      </QueryClientProvider>
    );
  };

  const mockCaseDetail = {
    id: 'case_909',
    title: 'High Velocity Synthetic Identity Probe',
    status: 'investigating',
    priority: 'high',
    assigned_to: 'analyst_lead',
    alert_ids: ['alt_909'],
    evidence_ids: [],
    notes: [
      {
        id: 'note_1',
        case_id: 'case_909',
        author: 'analyst_lead',
        content: 'High velocity observed across bank_alpha and bank_beta.',
        created_at: '2026-08-14T08:00:00Z',
      },
    ],
    timeline: [
      {
        id: 'evt_1',
        case_id: 'case_909',
        event_type: 'created',
        description: 'Case auto-generated by ML ensemble alert',
        created_by: 'system',
        created_at: '2026-08-14T07:30:00Z',
      },
    ],
    created_at: '2026-08-14T07:30:00Z',
    updated_at: '2026-08-14T08:00:00Z',
    closed_at: null,
    total_risk_score: 840,
    duration_hours: 4.5,
    is_open: true,
  };

  beforeEach(() => {
    vi.restoreAllMocks();

    vi.spyOn(apiClient, 'get').mockImplementation(async (url: string) => {
      if (url.includes('/api/v1/cases/case_909/evidence')) {
        return {
          data: [
            {
              id: 'evi_01',
              case_id: 'case_909',
              evidence_type: 'document',
              title: '3-node structuring cluster proof',
              file_path: 'ipfs://bafybeiclk7.../subgraph.json',
              content_hash: '3f78a2c59d8e1234567890abcdef1234567890abcdef1234567890abcdef1234',
              uploaded_by: 'Analyst #402',
              uploaded_at: '2026-08-14T11:32:00Z',
            },
          ],
        } as any;
      }
      if (url.includes('/api/v1/cases/case_909')) {
        return { data: mockCaseDetail } as any;
      }
      return { data: [] } as any;
    });

    vi.spyOn(apiClient, 'post').mockImplementation(async () => {
      return {
        data: {
          id: 'evi_02',
          case_id: 'case_909',
          evidence_type: 'document',
          title: 'Cross-Bank Transfer Log',
          file_path: 'uploads/transfer_log.csv',
          content_hash: '8f90a2c59d8e1234567890abcdef1234567890abcdef1234567890abcdef1234',
          uploaded_by: 'Analyst Lead',
          uploaded_at: '2026-08-14T11:35:00Z',
        },
      } as any;
    });
  });

  it('renders case detail with timeline, cryptographic evidence ledger, and allows adding evidence', async () => {
    const Wrapper = createWrapper('/cases/case_909');
    render(<Wrapper />);

    await waitFor(() => {
      expect(screen.getByText(/High Velocity Synthetic Identity Probe/i)).toBeInTheDocument();
    });

    expect(screen.getByText(/Timeline Events/i)).toBeInTheDocument();
    expect(screen.getByText(/Case auto-generated by ML ensemble alert/i)).toBeInTheDocument();
    expect(screen.getByText(/Case Evidence Registry/i)).toBeInTheDocument();

    const titleInput = screen.getByPlaceholderText(/e\.g\. Identity Proof/i);
    const pathInput = screen.getByPlaceholderText(/e\.g\. uploads\/id\.pdf/i);
    const contentInput = screen.getByPlaceholderText(/Content string to hash\.\.\./i);

    fireEvent.change(titleInput, { target: { value: 'Cross-Bank Transfer Log' } });
    fireEvent.change(pathInput, { target: { value: 'uploads/transfer_log.csv' } });
    fireEvent.change(contentInput, { target: { value: 'test content payload' } });

    const submitBtn = screen.getByRole('button', { name: /\+ Register Evidence/i });
    fireEvent.click(submitBtn);

    expect(screen.getByText(/Case Evidence Registry/i)).toBeInTheDocument();
  });
});
